; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

; PUBLIC	?output_buffer@@3PADA				; output_buffer
_BSS	SEGMENT
?output_buffer@@3PADA DB 02800H DUP (?)			; output_buffer
_BSS	ENDS
CONST	SEGMENT
$SG6371	DB	' ', 00H
CONST	ENDS
; PUBLIC	?buildOutput@@YAXPBD@Z				; buildOutput
EXTRN	_strcat:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_token$ = 8						; size = 4
?buildOutput@@YAXPBD@Z PROC PRIVATE				; buildOutput
; File D:\GitHub\University\PP\folder_proj\Lab4\3.main on C++,  findEnv on c,  everything else on C++\buildOutput.cpp
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	cmp	DWORD PTR _token$[ebp], 0
	jne	SHORT $LN2@buildOutpu
	jmp	SHORT $LN1@buildOutpu
$LN2@buildOutpu:
; Line 9
	mov	eax, 1
	imul	ecx, eax, 0
	movsx	edx, BYTE PTR ?output_buffer@@3PADA[ecx]
	test	edx, edx
	je	SHORT $LN3@buildOutpu
; Line 10
	push	OFFSET $SG6371
	push	OFFSET ?output_buffer@@3PADA		; output_buffer
	call	_strcat
	add	esp, 8
$LN3@buildOutpu:
; Line 12
	mov	eax, DWORD PTR _token$[ebp]
	push	eax
	push	OFFSET ?output_buffer@@3PADA		; output_buffer
	call	_strcat
	add	esp, 8
$LN1@buildOutpu:
; Line 13
	pop	ebp
	ret	0
?buildOutput@@YAXPBD@Z ENDP				; buildOutput
_TEXT	ENDS
END
