; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

; PUBLIC	?nextToken@@YAPADPAD@Z				; nextToken
; Function compile flags: /Odtp
_TEXT	SEGMENT
_start$ = -4						; size = 4
_str$ = 8						; size = 4
?nextToken@@YAPADPAD@Z PROC PRIVATE				; nextToken
; File D:\GitHub\University\PP\folder_proj\Lab4\3.main on C++,  findEnv on c,  everything else on C++\nextToken.cpp
; Line 3
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 4
	cmp	DWORD PTR _str$[ebp], 0
	je	SHORT $LN5@nextToken
	mov	eax, DWORD PTR _str$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	jne	SHORT $LN4@nextToken
$LN5@nextToken:
	xor	eax, eax
	jmp	SHORT $LN1@nextToken
$LN4@nextToken:
; Line 6
	mov	edx, DWORD PTR _str$[ebp]
	mov	DWORD PTR _start$[ebp], edx
$LN2@nextToken:
; Line 7
	mov	eax, DWORD PTR _str$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN3@nextToken
	mov	edx, DWORD PTR _str$[ebp]
	movsx	eax, BYTE PTR [edx]
	cmp	eax, 59					; 0000003bH
	je	SHORT $LN3@nextToken
; Line 8
	mov	ecx, DWORD PTR _str$[ebp]
	add	ecx, 1
	mov	DWORD PTR _str$[ebp], ecx
; Line 9
	jmp	SHORT $LN2@nextToken
$LN3@nextToken:
; Line 10
	mov	edx, DWORD PTR _str$[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	je	SHORT $LN6@nextToken
; Line 11
	mov	ecx, DWORD PTR _str$[ebp]
	mov	BYTE PTR [ecx], 0
; Line 12
	mov	eax, DWORD PTR _str$[ebp]
	add	eax, 1
	jmp	SHORT $LN1@nextToken
$LN6@nextToken:
; Line 14
	xor	eax, eax
$LN1@nextToken:
; Line 15
	mov	esp, ebp
	pop	ebp
	ret	0
?nextToken@@YAPADPAD@Z ENDP				; nextToken
_TEXT	ENDS
END
