; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_findEnv
EXTRN	_strlen:PROC
EXTRN	_strncmp:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_len$1 = -8						; size = 4
_i$2 = -4						; size = 4
_name$ = 8						; size = 4
_envp$ = 12						; size = 4
_findEnv PROC
; File D:\GitHub\University\PP\folder_proj\Lab6\2.All source modules on C++\findEnv.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 5
	mov	DWORD PTR _i$2[ebp], 0
	jmp	SHORT $LN4@findEnv
$LN2@findEnv:
	mov	eax, DWORD PTR _i$2[ebp]
	add	eax, 1
	mov	DWORD PTR _i$2[ebp], eax
$LN4@findEnv:
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _envp$[ebp]
	cmp	DWORD PTR [edx+ecx*4], 0
	je	SHORT $LN3@findEnv
; Line 7
	mov	eax, DWORD PTR _name$[ebp]
	push	eax
	call	_strlen
	add	esp, 4
	mov	DWORD PTR _len$1[ebp], eax
; Line 8
	mov	ecx, DWORD PTR _len$1[ebp]
	push	ecx
	mov	edx, DWORD PTR _name$[ebp]
	push	edx
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _envp$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	push	edx
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN5@findEnv
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _envp$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	eax, DWORD PTR _len$1[ebp]
	movsx	ecx, BYTE PTR [edx+eax]
	cmp	ecx, 61					; 0000003dH
	jne	SHORT $LN5@findEnv
; Line 9
	mov	edx, DWORD PTR _i$2[ebp]
	mov	eax, DWORD PTR _envp$[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	mov	edx, DWORD PTR _len$1[ebp]
	lea	eax, DWORD PTR [ecx+edx+1]
	jmp	SHORT $LN1@findEnv
$LN5@findEnv:
; Line 11
	jmp	SHORT $LN2@findEnv
$LN3@findEnv:
; Line 12
	xor	eax, eax
$LN1@findEnv:
; Line 13
	mov	esp, ebp
	pop	ebp
	ret	0
_findEnv ENDP
_TEXT	ENDS
END
