; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?output_buffer@@3PADA				; output_buffer
_BSS	SEGMENT
?output_buffer@@3PADA DB 02800H DUP (?)			; output_buffer
_BSS	ENDS
CONST	SEGMENT
$SG6371	DB	' ', 00H
CONST	ENDS
PUBLIC	?buildOutput@@YAXPBD@Z				; buildOutput
EXTRN	_strcat:PROC
; Function compile flags: /Odsp
_TEXT	SEGMENT
_token$ = 8						; size = 4
?buildOutput@@YAXPBD@Z PROC				; buildOutput
; File D:\GitHub\University\PP\folder_proj\Lab7\2.All source modules on C++\buildOutput.cpp
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	cmp	DWORD PTR _token$[ebp], 0
	jne	SHORT $LN2@buildOutpu
	jmp	SHORT $LN1@buildOutpu
$LN2@buildOutpu:
; Line 9
	xor	eax, eax
	inc	eax
	imul	eax, eax, 0
	movsx	eax, BYTE PTR ?output_buffer@@3PADA[eax]
	test	eax, eax
	je	SHORT $LN3@buildOutpu
; Line 10
	push	OFFSET $SG6371
	push	OFFSET ?output_buffer@@3PADA		; output_buffer
	call	_strcat
	pop	ecx
	pop	ecx
$LN3@buildOutpu:
; Line 12
	push	DWORD PTR _token$[ebp]
	push	OFFSET ?output_buffer@@3PADA		; output_buffer
	call	_strcat
	pop	ecx
	pop	ecx
$LN1@buildOutpu:
; Line 13
	pop	ebp
	ret	0
?buildOutput@@YAXPBD@Z ENDP				; buildOutput
_TEXT	ENDS
END
