; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?output_buffer@@3PADA				; output_buffer
_BSS	SEGMENT
?output_buffer@@3PADA DB 02800H DUP (?)			; output_buffer
_BSS	ENDS
PUBLIC	?buildOutput@@YAXPBD@Z				; buildOutput
PUBLIC	??_C@_01CLKCMJKC@?5@				; `string'
EXTRN	_strcat:PROC
;	COMDAT ??_C@_01CLKCMJKC@?5@
CONST	SEGMENT
??_C@_01CLKCMJKC@?5@ DB ' ', 00H			; `string'
CONST	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?buildOutput@@YAXPBD@Z
_TEXT	SEGMENT
_token$ = 8						; size = 4
?buildOutput@@YAXPBD@Z PROC				; buildOutput, COMDAT
; File D:\GitHub\University\PP\folder_proj\Lab7\2.All source modules on C++\buildOutput.cpp
; Line 7
	cmp	DWORD PTR _token$[esp-4], 0
	je	SHORT $LN1@buildOutpu
; Line 9
	cmp	BYTE PTR ?output_buffer@@3PADA, 0
	push	esi
	mov	esi, OFFSET ?output_buffer@@3PADA	; output_buffer
	je	SHORT $LN3@buildOutpu
; Line 10
	push	OFFSET ??_C@_01CLKCMJKC@?5@
	push	esi
	call	_strcat
	pop	ecx
	pop	ecx
$LN3@buildOutpu:
; Line 12
	push	DWORD PTR _token$[esp]
	push	esi
	call	_strcat
	pop	ecx
	pop	ecx
	pop	esi
$LN1@buildOutpu:
; Line 13
	ret	0
?buildOutput@@YAXPBD@Z ENDP				; buildOutput
_TEXT	ENDS
END
