; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_C@_0BN@NFCGNIGG@Env?5Name?3?5?$CFs?6Env?5Value?3?5?$CFs?6?6@ ; `string'
PUBLIC	??_C@_0BB@JHLLOAHP@?$CFs?5is?5not?5found?6@	; `string'
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	?findEnv@@YAPADPBDQAPAD@Z:PROC			; findEnv
EXTRN	?nextToken@@YAPADPAD@Z:PROC			; nextToken
EXTRN	?buildOutput@@YAXPBD@Z:PROC			; buildOutput
EXTRN	?output_buffer@@3PADA:BYTE			; output_buffer
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT ??_C@_0BB@JHLLOAHP@?$CFs?5is?5not?5found?6@
CONST	SEGMENT
??_C@_0BB@JHLLOAHP@?$CFs?5is?5not?5found?6@ DB '%s is not found', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@NFCGNIGG@Env?5Name?3?5?$CFs?6Env?5Value?3?5?$CFs?6?6@
CONST	SEGMENT
??_C@_0BN@NFCGNIGG@Env?5Name?3?5?$CFs?6Env?5Value?3?5?$CFs?6?6@ DB 'Env N'
	DB	'ame: %s', 0aH, 'Env Value: %s', 0aH, 0aH, 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_envp$ = 16						; size = 4
_main	PROC						; COMDAT
; File D:\GitHub\University\PP\folder_proj\Lab7\2.All source modules on C++\lab3.cpp
; Line 7
	push	ebp
; Line 8
	mov	ebp, DWORD PTR _argc$[esp]
	cmp	ebp, 1
	jle	SHORT $LN18@main
	push	ebx
	mov	ebx, DWORD PTR _argv$[esp+4]
	push	esi
	add	ebx, 4
	dec	ebp
	push	edi
$LL4@main:
; Line 9
	push	DWORD PTR _envp$[esp+12]
	push	DWORD PTR [ebx]
	call	?findEnv@@YAPADPBDQAPAD@Z		; findEnv
	mov	esi, eax
	add	esp, 8
; Line 10
	test	esi, esi
	je	SHORT $LN7@main
; Line 13
	mov	BYTE PTR ?output_buffer@@3PADA, 0
$LL5@main:
; Line 15
	push	esi
	call	?nextToken@@YAPADPAD@Z			; nextToken
; Line 17
	push	esi
	mov	edi, eax
	mov	BYTE PTR ?output_buffer@@3PADA, 0
	call	?buildOutput@@YAXPBD@Z			; buildOutput
; Line 18
	push	OFFSET ?output_buffer@@3PADA		; output_buffer
	push	DWORD PTR [ebx]
	push	OFFSET ??_C@_0BN@NFCGNIGG@Env?5Name?3?5?$CFs?6Env?5Value?3?5?$CFs?6?6@
	call	_printf
	add	esp, 20					; 00000014H
; Line 19
	mov	esi, edi
	test	edi, edi
	jne	SHORT $LL5@main
; Line 21
	jmp	SHORT $LN2@main
$LN7@main:
; Line 22
	push	DWORD PTR [ebx]
	push	OFFSET ??_C@_0BB@JHLLOAHP@?$CFs?5is?5not?5found?6@
	call	_printf
	add	esp, 8
$LN2@main:
; Line 8
	add	ebx, 4
	sub	ebp, 1
	jne	SHORT $LL4@main
	pop	edi
	pop	esi
	pop	ebx
$LN18@main:
; Line 26
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdio.h
; Line 956
	push	esi
; Line 960
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 645
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 962
	pop	esi
; Line 963
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdio.h
; Line 645
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_stdio_config.h
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
