; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_output_buffer
_BSS	SEGMENT
_output_buffer DB 02800H DUP (?)
_BSS	ENDS
CONST	SEGMENT
$SG6379	DB	' ', 00H
CONST	ENDS
PUBLIC	_buildOutput
EXTRN	_strcat:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_token$ = 8						; size = 4
_buildOutput PROC
; File D:\GitHub\University\PP\folder_proj\Lab6\3.main on C++,  findEnv on c,  everything else on C++\buildOutput.cpp
; Line 7
	push	ebp
	mov	ebp, esp
; Line 8
	cmp	DWORD PTR _token$[ebp], 0
	jne	SHORT $LN2@buildOutpu
	jmp	SHORT $LN1@buildOutpu
$LN2@buildOutpu:
; Line 10
	mov	eax, 1
	imul	ecx, eax, 0
	movsx	edx, BYTE PTR _output_buffer[ecx]
	test	edx, edx
	je	SHORT $LN3@buildOutpu
; Line 11
	push	OFFSET $SG6379
	push	OFFSET _output_buffer
	call	_strcat
	add	esp, 8
$LN3@buildOutpu:
; Line 13
	mov	eax, DWORD PTR _token$[ebp]
	push	eax
	push	OFFSET _output_buffer
	call	_strcat
	add	esp, 8
$LN1@buildOutpu:
; Line 14
	pop	ebp
	ret	0
_buildOutput ENDP
_TEXT	ENDS
END
