; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_output_buffer:BYTE:02800H
_DATA	ENDS
PUBLIC	_buildOutput
EXTRN	_strcat:PROC
_DATA	SEGMENT
$SG10547 DB	' ', 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_token$ = 8						; size = 4
_buildOutput PROC
; File D:\GitHub\University\PP\folder_proj\Lab6\6.main on C,  findEnv on C++,  everything else on C\buildOutput.c
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	cmp	DWORD PTR _token$[ebp], 0
	jne	SHORT $LN2@buildOutpu
	jmp	SHORT $LN1@buildOutpu
$LN2@buildOutpu:
; Line 9
	mov	eax, 1
	imul	ecx, eax, 0
	movsx	edx, BYTE PTR _output_buffer[ecx]
	test	edx, edx
	je	SHORT $LN3@buildOutpu
; Line 10
	push	OFFSET $SG10547
	push	OFFSET _output_buffer
	call	_strcat
	add	esp, 8
$LN3@buildOutpu:
; Line 12
	mov	eax, DWORD PTR _token$[ebp]
	push	eax
	push	OFFSET _output_buffer
	call	_strcat
	add	esp, 8
$LN1@buildOutpu:
; Line 13
	pop	ebp
	ret	0
_buildOutput ENDP
_TEXT	ENDS
END
