; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	\\.\nul
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

; PUBLIC	___local_stdio_printf_options
; PUBLIC	__vfprintf_l
; PUBLIC	_printf
PUBLIC	_main
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	_findEnv:PROC
EXTRN	_nextToken:PROC
EXTRN	_buildOutput:PROC
EXTRN	_output_buffer:BYTE
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_DATA	SEGMENT
$SG10567 DB	'Env Name: %s', 0aH, 'Env Value: %s', 0aH, 0aH, 00H
	ORG $+3
$SG10568 DB	'%s is not found', 0aH, 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_next$1 = -16						; size = 4
_env_value$2 = -12					; size = 4
_remaining$3 = -8					; size = 4
_i$4 = -4						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_envp$ = 16						; size = 4
_main	PROC
; File D:\GitHub\University\PP\folder_proj\Lab6\6.main on C,  findEnv on C++,  everything else on C\main.c
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
; Line 8
	mov	DWORD PTR _i$4[ebp], 1
	jmp	SHORT $LN4@main
$LN2@main:
	mov	eax, DWORD PTR _i$4[ebp]
	add	eax, 1
	mov	DWORD PTR _i$4[ebp], eax
$LN4@main:
	mov	ecx, DWORD PTR _i$4[ebp]
	cmp	ecx, DWORD PTR _argc$[ebp]
	jge	$LN3@main
; Line 9
	mov	edx, DWORD PTR _envp$[ebp]
	push	edx
	mov	eax, DWORD PTR _i$4[ebp]
	mov	ecx, DWORD PTR _argv$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	push	edx
	call	_findEnv
	add	esp, 8
	mov	DWORD PTR _env_value$2[ebp], eax
; Line 10
	cmp	DWORD PTR _env_value$2[ebp], 0
	je	SHORT $LN7@main
; Line 11
	mov	eax, DWORD PTR _env_value$2[ebp]
	mov	DWORD PTR _remaining$3[ebp], eax
; Line 13
	mov	ecx, 1
	imul	edx, ecx, 0
	mov	BYTE PTR _output_buffer[edx], 0
$LN5@main:
; Line 14
	cmp	DWORD PTR _remaining$3[ebp], 0
	je	SHORT $LN6@main
; Line 15
	mov	eax, DWORD PTR _remaining$3[ebp]
	push	eax
	call	_nextToken
	add	esp, 4
	mov	DWORD PTR _next$1[ebp], eax
; Line 16
	mov	ecx, 1
	imul	edx, ecx, 0
	mov	BYTE PTR _output_buffer[edx], 0
; Line 17
	mov	eax, DWORD PTR _remaining$3[ebp]
	push	eax
	call	_buildOutput
	add	esp, 4
; Line 18
	push	OFFSET _output_buffer
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _argv$[ebp]
	mov	eax, DWORD PTR [edx+ecx*4]
	push	eax
	push	OFFSET $SG10567
	call	_printf
	add	esp, 12					; 0000000cH
; Line 19
	mov	ecx, DWORD PTR _next$1[ebp]
	mov	DWORD PTR _remaining$3[ebp], ecx
; Line 20
	jmp	SHORT $LN5@main
$LN6@main:
; Line 21
	jmp	SHORT $LN8@main
$LN7@main:
; Line 22
	mov	edx, DWORD PTR _i$4[ebp]
	mov	eax, DWORD PTR _argv$[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	push	ecx
	push	OFFSET $SG10568
	call	_printf
	add	esp, 8
$LN8@main:
; Line 24
	jmp	$LN2@main
$LN3@main:
; Line 25
	xor	eax, eax
; Line 26
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC PRIVATE						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdio.h
; Line 956
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 959
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 960
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 961
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 962
	mov	eax, DWORD PTR __Result$[ebp]
; Line 963
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC PRIVATE					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\stdio.h
; Line 644
	push	ebp
	mov	ebp, esp
; Line 645
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC PRIVATE			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_stdio_config.h
; Line 90
	push	ebp
	mov	ebp, esp
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
